// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	DiscordSkus  string
	PatreonTiers string
	PremiumCodes string
	PremiumSlots string
}{
	DiscordSkus:  "discord_skus",
	PatreonTiers: "patreon_tiers",
	PremiumCodes: "premium_codes",
	PremiumSlots: "premium_slots",
}
